# Generated by Django 4.2.1 on 2023-06-23 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAnimal',
            fields=[
                ('id_tipoA', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipoA', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('sku', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('proveedor', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('imagen_url', models.ImageField(upload_to='imagenesProducto')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.categoria')),
                ('id_tipoA', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='tienda.tipoanimal')),
            ],
        ),
    ]
