# Generated by Django 4.2.1 on 2023-06-23 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_tipoA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.tipoanimal'),
        ),
    ]
