# Generated by Django 4.2.1 on 2023-06-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_producto_id_tipoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoanimal',
            name='id_tipoA',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
